version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres
    # restart: always
    environment:
      POSTGRES_USER: postgresadmin
      POSTGRES_PASSWORD: postgresp@ss
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      env_developer: {}

volumes:
  postgres-data:

networks:
  env_developer:
    external: true
