services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    environment:
      TZ: "Asia/Bangkok"
      # NPM_ADMIN_EMAIL: "admin@domain.com"
      # NPM_ADMIN_PASSWORD: "Adminp@ss99"
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

    networks:
      - proxy

networks:
  proxy:
    external: true